const Students = [
    {
        id: '1',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '2',
        name: "يوسف شهاب يوسف عبد الحفيظ",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '3',
        name: "اسلام محمد السيد جمعة حسن",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '4',
        name: "محمد محمود محمد الدولي",
        image: 'student.png',
        section: 'علوم حاسب',
        squad: 'الثالثة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '5',
        name: "احمد سعيد محمد عبد اللطيف",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الثانية',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '6',
        name: "احمد صبري بدر شحاته",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الثانية',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '7',
        name: "احمد عاطف شعبان احمد الجندي",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الثانية',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '8',
        name: "احمد عباس احمد عباس حنيظة",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '9',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '10',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '11',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '12',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '13',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '14',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '15',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '16',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '17',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '18',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '19',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '20',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '21',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '22',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '23',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '24',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '25',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
    {
        id: '26',
        name: "احمد ماهر احمد ابراهيم شعيب",
        image: 'student.png',
        section: 'نظم ومعلومات ادارية	',
        squad: 'الرابعة',
        StudyCase: 'مستجد',
        Spec: 'عام',
    },
]
export default Students